### ISSUE TITLE
reporte de practica 2

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/practica-de-visual-studio-Nayee123-1#4]
[TOPICOS_AVANZADOS_REPORTE_PRACTICA_2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Nayee123-1/files/6191296/TOPICOS_AVANZADOS_REPORTE_PRACTICA_2.pdf)

**Comment by Rosa218** [comment]
Un buen trabajo 
Obtuvo la calificación de 20/20
Califico: Rosa Salazar Doroteo

**Comment by josealfredo79** [comment]
esta bien hecho y revisado..

**Comment by josealfredo79** [comment]
esta bien hecho y revisado..

**Comment by josealfredo79** [comment]
esta bien hecho y revisado..
